INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=72&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Equipment','Category:Equipment','nav-only category page with subcategory listings','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=641&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=111&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=15&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Key_Items','Key_Items','nav-only page listing key items category without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Abyss_Item','Abyss_Item','nav-only category listing without substantive item details','item'),
('https://crimsondesert.wiki.fextralife.com/Horn_Thief','Horn_Thief','nav-only list of key items without substantive content about Horn Thief itself','item'),
('https://crimsondesert.wiki.fextralife.com/Key','Key','nav-only page listing key items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Lost_Letter','Lost_Letter','nav-only list of key items without substantive content about Lost Letter itself','item'),
('https://crimsondesert.wiki.fextralife.com/Seal_of_Greed_-_Goldleaf_Merchant_Guild','Seal_of_Greed_-_Goldleaf_Merchant_Guild','nav-only page listing key items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Stolen_Cows','Stolen_Cows','nav-only page listing key items without quest details','item'),
('https://crimsondesert.wiki.fextralife.com/Tavern_Ledger','Tavern_Ledger','nav-only list of items without substantive content about the Tavern Ledger itself','item'),
('https://crimsondesert.wiki.fextralife.com/Ugmon%27s_Note','Ugmon''s_Note','nav-only, no substantive content about the item itself','item'),
('https://crimsondesert.wiki.fextralife.com/Unsealed_Letter','Unsealed_Letter','nav-only page with item list, no substantive content about the item itself','item'),
('https://crimsondesert.wiki.fextralife.com/Wisdom_between_Donation_and_Fruition','Wisdom_between_Donation_and_Fruition','nav-only page listing items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Locations','Locations','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Arboria_Craftshop','Arboria_Craftshop','nav-only location stub with minimal substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/NPCs','NPCs','nav-only page listing NPC mechanics, not a specific NPC','character'),
('https://crimsondesert.wiki.fextralife.com/Calphade_Gate','Calphade_Gate','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=324&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=523&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=404&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=884&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=312&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=304&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=539&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=305&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=306&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=313&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=775&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=314&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=315&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=551&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=793&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=528&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=316&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=53&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=188&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=319&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=463&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=327&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=13&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=66&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=262&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=552&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=555&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=537&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Precipice+of+Echoes+Ruins','Precipice of Echoes Ruins','nav-only page listing challenges/locations without substantive content about the specific location itself.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=455&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=510&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=928&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=511&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=933&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=479&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=941&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=934&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=449&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=525&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=517&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=541&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Delkin','Delkin','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Renee','Renee','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=197&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=376&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Annabella','Annabella','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=942&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood+Waterside+Ruins','Duskwood Waterside Ruins','nav-only page with quest/location list, no substantive content about the location itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1431&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1411&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1013&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=936&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=935&amp;code=mapA','Interactive Map','nav-only page with map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=932&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=937&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=938&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Abacus','Abacus','nav-only page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Horse_Items','Category:Horse_Items','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Notepad','Notepad','nav-only page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/Equipment','Equipment','nav-only search results page with no substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Abyss_Core_1_Abyss_Core_Gallery','Subcontent:Abyss_Core_1_Abyss_Core_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Accessories_1_Accessories_Gallery','Subcontent:Accessories_1_Accessories_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Accessories_2_Accessories_Table','Subcontent:Accessories_2_Accessories_Table','nav-only page with minimal substantive content about accessories','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Pets_1_Pet_Types','Subcontent:Pets_1_Pet_Types','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Pets_2_Pet_Equipment','Subcontent:Pets_2_Pet_Equipment','nav-only with item list; no substantive mechanics or lore','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Tools_1_Tools_Gallery','Subcontent:Tools_1_Tools_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Tools_2_Tools_Table','Subcontent:Tools_2_Tools_Table','nav-only page listing tools without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Unique_Weapons','Unique_Weapons','nav-only page listing weapon categories without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Alchemy_Recipes','Alchemy_Recipes','nav-only list of recipes without substantive details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Items','Category:Items','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:NPCs','Category:NPCs','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Recovery_Items','Category:Recovery_Items','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Drake_Wells','Drake_Wells','nav-only; excerpt is mostly NPC list without substantive Drake Wells content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Grania','Grania','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Grimrak','Grimrak','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Groks','Groks','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=507&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=509&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=303&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1812&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=138&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1501&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=514&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=444&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=446&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=533&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1427&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1632&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=219&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=447&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=208&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=223&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=221&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=241&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=217&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=294&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=220&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=519&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=198&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=199&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=244&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=156&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=243&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=157&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=158&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=145&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=149&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=146&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=143&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=160&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=151&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=114&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=289&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1417&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1634&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1653&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=364&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=127&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=142&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=302&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=529&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=532&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=530&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=531&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=296&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=308&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=297&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=309&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=298&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=310&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=299&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=311&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=259&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=366&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=139&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=194&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=136&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=365&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=141&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=210&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=167&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=548&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1413&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=549&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=164&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1403&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1412&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=168&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1668&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1753&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1684&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1113&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1667&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1700&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1666&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1685&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Bosses','Bosses','nav-only or system overview, not a specific boss','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1589&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1592&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1623&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1629&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1375&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Merchants','Merchants','nav-only list of merchants without substantive details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Consumables','Consumables','nav-only page listing consumable categories without specific item details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Force+Palm','Force Palm','nav-only list of skills without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Blacksmiths','Blacksmiths','nav-only page listing blacksmith NPCs without substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Guides+%26+Walkthrough','Guides & Walkthrough','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/FAQs','FAQs','nav-only page with system specs and links, no substantive game content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Crimson_Desert_Wiki','Crimson_Desert_Wiki','nav-only; excerpt is wiki homepage with general boss overview, not a specific subject.','boss'),
('https://crimsondesert.wiki.fextralife.com/Rock_Paper_Scissors','Rock_Paper_Scissors','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/New_Player_Help','New_Player_Help','nav-only guide page with mixed topics','mechanic'),
('https://crimsondesert.wiki.fextralife.com/General_Information','General_Information','nav-only page with minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/DLC','DLC','nav-only page listing DLC editions and items without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:General_Information','Category:General_Information','nav-only category page with minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_2_Xbox_Controls','Subcontent:Controls_2_Xbox_Controls','nav-only, control mapping reference without substantive gameplay explanation','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_3_PC_Controls','Subcontent:Controls_3_PC_Controls','nav-only, control mapping reference without substantive game content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_4_Tab_4','Subcontent:Controls_4_Tab_4','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Arm_Wrestling','Arm_Wrestling','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Where_Rumors_Gather','Where_Rumors_Gather','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Abyss_without_Balance','Abyss_without_Balance','nav-only','quest')
ON CONFLICT (source_url) DO NOTHING;

INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Abyss_Cresset_of_Meandering_Hills','Abyss_Cresset_of_Meandering_Hills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Missing_Companion','Missing_Companion','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Fresh_Start','A_Fresh_Start','nav-only page listing quest names without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Clear_Soup_(Recipe)','Clear_Soup_(Recipe)','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Greymanes_Reunited','Greymanes_Reunited','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Items','Items','nav-only page listing crafting/cooking systems, not a specific item','item'),
('https://crimsondesert.wiki.fextralife.com/House_Alfonso','House_Alfonso','nav-only page with faction listing, minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Goddess_of_Abundance','Goddess_of_Abundance','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/The_Hunter%27s_Path','The_Hunter''s_Path','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_2_Greymanes','Subcontent:Faction_Quests_2_Greymanes','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_3_Pailune','Subcontent:Faction_Quests_3_Pailune','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_4_Demeniss','Subcontent:Faction_Quests_4_Demeniss','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_5_Delesyia','Subcontent:Faction_Quests_5_Delesyia','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_6_Crimson_Desert','Subcontent:Faction_Quests_6_Crimson_Desert','nav-only page listing quest names without substantive details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Quests','Category:Quests','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Root%27s_End_(Challenge)','Root''s_End_(Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sanctorum_of_Insight_(Challenge)','Sanctorum_of_Insight_(Challenge)','nav-only list with minimal substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Detailed_Glance','A_Detailed_Glance','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Haven_Past_the_Snowfall','Haven_Past_the_Snowfall','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Duskwood_Hill_Ruins','Duskwood_Hill_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering_Hills_Ruins','Meandering_Hills_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sunrise_Plains_Ruins','Sunrise_Plains_Ruins','nav-only page listing quests/challenges without substantive location details','quest'),
('https://crimsondesert.wiki.fextralife.com/Arboria_Forest_Ruins','Arboria_Forest_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire_of_Insight_(Challenge)','Spire_of_Insight_(Challenge)','nav-only page listing challenges/locations without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire_of_Clockwork_(Challenge)','Spire_of_Clockwork_(Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Rainbow_Across_the_Sky','Rainbow_Across_the_Sky','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Flash','Flash','nav-only; mostly challenge list without substantive Flash content','quest'),
('https://crimsondesert.wiki.fextralife.com/Recipes','Recipes','nav-only page listing recipe categories without specific recipe details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Animal_Meat','Animal_Meat','nav-only, appears to be a list of quests/items without substantive content about Animal Meat itself','quest'),
('https://crimsondesert.wiki.fextralife.com/Silver_Trigger','Silver_Trigger','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Steel_Fist','Steel_Fist','nav-only page with list of quest/location names','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Bloom_of_High_Stakes','A_Bloom_of_High_Stakes','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Guides_and_Walkthrough','Guides_and_Walkthrough','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/In_Ashes','In_Ashes','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Realm_of_Uncertainty','Realm_of_Uncertainty','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Characters','Characters','nav-only page listing characters without substantive detail','character'),
('https://crimsondesert.wiki.fextralife.com/Character_Information','Character_Information','nav-only page listing character skills without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Delesyia','Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Crimson_Desert','Crimson_Desert','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Sanctorum+of+Insight+(Challenge)','Sanctorum of Insight (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Axiom+Archive+(Challenge)','Axiom Archive (Challenge)','nav-only page with link lists, no substantive content about Axiom Archive itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Crescent+Skybridge+(Challenge)','Crescent Skybridge (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Arboria+Forest+Ruins','Arboria Forest Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Root''s+End+(Challenge)','Root''s End (Challenge)','excerpt is nav-only list without substantive content about Root''s End','quest'),
('https://crimsondesert.wiki.fextralife.com/Haven+Past+the+Snowfall','Haven Past the Snowfall','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood+Hill+Ruins','Duskwood Hill Ruins','nav-only - excerpt is primarily a list of linked page names without substantive content about the location itself.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Sunrise+Plains+Ruins','Sunrise Plains Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Dragon''s+Stone+Chamber+Ruins','Dragon''s Stone Chamber Ruins','nav-only page with quest/location list, no substantive content about the ruins themselves','quest'),
('https://crimsondesert.wiki.fextralife.com/Keeping+Balance+on+the+Wind','Keeping Balance on the Wind','nav-only page with quest/location list, no substantive content about the titled topic','quest'),
('https://crimsondesert.wiki.fextralife.com/Factions','Factions','nav-only page listing factions without substantive details','boss'),
('https://crimsondesert.wiki.fextralife.com/Dancing+Blade+Shining+Shield+I','Dancing Blade Shining Shield I','nav-only page with link list, no substantive content about the item itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Animal+Meat','Animal Meat','excerpt is nav-only list without item details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/A+Bloom+of+High+Stakes','A Bloom of High Stakes','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Awestruck','Awestruck','nav-only page listing quests without substantive content about a specific subject.','quest'),
('https://crimsondesert.wiki.fextralife.com/Return','Return','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Howling+Hill','Howling Hill','nav-only - primarily lists quests without substantive location details','character'),
('https://crimsondesert.wiki.fextralife.com/Shield+of+Unchanging+Will+I','Shield of Unchanging Will I','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Side_Quests','Side_Quests','nav-only page listing side quests without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_1_Main_Bosses','Subcontent:Bosses_1_Main_Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_2_Side_Bosses','Subcontent:Bosses_2_Side_Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_3_Bosses_by_Region','Subcontent:Bosses_3_Bosses_by_Region','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_1_Duchy_of_Hernand','Subcontent:Factions_1_Duchy_of_Hernand','nav-only page with minimal substantive content about factions','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_2_Tribal_State_of_Pailune','Subcontent:Factions_2_Tribal_State_of_Pailune','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_3_Continent_of_Pywel','Subcontent:Factions_3_Continent_of_Pywel','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_1_Animals_Gallery','Subcontent:Lifeforms_1_Animals_Gallery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_2_Land_Animals','Subcontent:Lifeforms_2_Land_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_3_Flying_Animals','Subcontent:Lifeforms_3_Flying_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_4_Aquatic_Animals','Subcontent:Lifeforms_4_Aquatic_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_5_Insects_and_Arthropods','Subcontent:Lifeforms_5_Insects_and_Arthropods','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Locations_1_List_of_all_Locations','Subcontent:Locations_1_List_of_all_Locations','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Locations_2_Locations_Gallery','Subcontent:Locations_2_Locations_Gallery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_3_Demeniss','Subcontent:NPCs_3_Demeniss','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_4_Delesyia','Subcontent:NPCs_4_Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_5_Crimson_Desert','Subcontent:NPCs_5_Crimson_Desert','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_6_The_Abyss','Subcontent:NPCs_6_The_Abyss','nav-only page listing NPCs with minimal substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Supply_Tent','Supply_Tent','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/The_Missing_Seal','The_Missing_Seal','nav-only page listing quest names without substantive quest details','character'),
('https://crimsondesert.wiki.fextralife.com/Warspike_Spearmaker','Warspike_Spearmaker','nav-only page with location listings, no substantive content about the subject','character'),
('https://crimsondesert.wiki.fextralife.com/Projectiles','Projectiles','nav-only page with minimal substantive content about projectiles','item'),
('https://crimsondesert.wiki.fextralife.com/Tools','Tools','nav-only category page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Armor','Armor','nav-only page with minimal substantive content about armor mechanics or specific items.','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=526&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=147&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=931&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1608&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1646&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Halssius_Apothecary','Halssius_Apothecary','nav-only location listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=542&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1815&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=387&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=382&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=398&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1416&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Trial_After_Trial','Trial_After_Trial','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Dark_Veil','The_Dark_Veil','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Kidnapped_Healer','Kidnapped_Healer','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Return_of_the_Comrade','Return_of_the_Comrade','excerpt is nav-only, no quest content visible','quest'),
('https://crimsondesert.wiki.fextralife.com/Traces_in_the_Manor','Traces_in_the_Manor','excerpt is nav-only, no substantive quest content visible','quest'),
('https://crimsondesert.wiki.fextralife.com/Hope_After_the_Draught','Hope_After_the_Draught','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Bustling_Hill','Bustling_Hill','nav-only page listing quests without substantive location info','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Words_of_Alustin','The_Words_of_Alustin','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Demenissian_Delegation','Demenissian_Delegation','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Three_Saints%27_Falls','Three_Saints''_Falls','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Anvil_Riverside_Terrace','Anvil_Riverside_Terrace','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Axiom_Archive','Axiom_Archive','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering_Hills','Meandering_Hills','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Hernand_Farmhouse','Hernand_Farmhouse','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Capra_Pasture','Capra_Pasture','nav-only location page with minimal substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Goldleaf_Tradepost','Goldleaf_Tradepost','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Goldleaf_Guildhouse','Goldleaf_Guildhouse','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Scrapfold','The_Scrapfold','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Coalvale_Workshop','Coalvale_Workshop','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meshley_Trapsmith','Meshley_Trapsmith','nav-only page listing locations without substantive content about Meshley Trapsmith','quest'),
('https://crimsondesert.wiki.fextralife.com/Demeniss','Demeniss','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Wycliffe_Mappery','Wycliffe_Mappery','nav-only page listing locations without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Arrow_(Recipe)','Arrow_(Recipe)','nav-only list without recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Battered_Fish_(Recipe)','Battered_Fish_(Recipe)','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Battered_Vegetables_(Recipe)','Battered_Vegetables_(Recipe)','excerpt is nav-only list, no recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Lioncrest_Manor','Lioncrest_Manor','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Phoniel_Ranch','Phoniel_Ranch','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Thalwynd','Thalwynd','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/The_Sage%27s_Peak','The_Sage''s_Peak','nav-only location page with minimal substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Vellua','Vellua','nav-only page listing locations without substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Accessories','Accessories','nav-only category page listing accessories without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=407&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Sunset+Valley','Sunset Valley','nav-only page listing locations without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Axiom+Archive','Axiom Archive','nav-only page listing locations without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1670&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1669&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1593&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1548&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1549&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1566&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1540&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1550&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1564&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=170&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=443&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=442&amp;code=mapA','Interactive Map','nav-only page with general tracker/tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=368&amp;code=mapA','Interactive Map','nav-only page with general tool description, not specific content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=360&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=369&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=445&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=363&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=371&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=392&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=393&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=543&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1536&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=984&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=451&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=373&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=396&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=508&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=370&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=405&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=402&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=410&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=381&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=379&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1418&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=395&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=386&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=413&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1405&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=388&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=415&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1502&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1503&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=372&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=357&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1492&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1591&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1496&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1497&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1498&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1499&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1654&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1750&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1777&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=78&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=960&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1810&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1799&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1649&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=502&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=544&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1806&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1811&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering+Hills','Meandering Hills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1804&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1802&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1803&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1807&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=564&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1797&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1801&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=515&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1805&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1808&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest')
ON CONFLICT (source_url) DO NOTHING;

INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1652&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=513&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=538&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire+of+Insight+(Challenge)','Spire of Insight (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sword+of+Trials+III','Sword of Trials III','nav-only page with challenge listings, minimal item details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Spire+of+Ringing+Truth+(Challenge)','Spire of Ringing Truth (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=239&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=350&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=351&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1406&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=399&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=416&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=427&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Theoric','Theoric','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Timberturner_Wainwright','Timberturner_Wainwright','nav-only page with ingredient lists and location links','recipe'),
('https://crimsondesert.wiki.fextralife.com/Tool_Blueprints','Tool_Blueprints','nav-only list of recipes without substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Ugmon','Ugmon','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Water_Strider','Water_Strider','nav-only list of gatherables without substantive Water Strider info','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Character_Information','Category:Character_Information','nav-only category page with no substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Characters','Category:Characters','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Kliff_Skills','Category:Kliff_Skills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Skills','Category:Skills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Precipice_of_Echoes_Ruins','Precipice_of_Echoes_Ruins','nav-only - excerpt is primarily a list of linked page names without substantive location information.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood_Waterside_Ruins','Duskwood_Waterside_Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Steel_Mountains_Ruins','Steel_Mountains_Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/World_Information','World_Information','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Kearush_the_Slayer','Kearush_the_Slayer','excerpt is nav-only (boss list without strategy details)','boss'),
('https://crimsondesert.wiki.fextralife.com/Tenebrum','Tenebrum','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Abyss_Nexus','Abyss_Nexus','nav-only list of Abyss Nexus locations without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map','Interactive_Map','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Lifeforms','Lifeforms','nav-only or ingredient list without gameplay context','character'),
('https://crimsondesert.wiki.fextralife.com/Lore','Lore','nav-only page with minimal substantive lore content','boss'),
('https://crimsondesert.wiki.fextralife.com/Special:Categories','Special:Categories','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Enemies','Enemies','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Reed_Devil_(Faction)','Reed_Devil_(Faction)','nav-only; mostly faction list without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Southern_Bandits','Southern_Bandits','nav-only page listing factions without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Black_Bears','Black_Bears','nav-only page with faction listings, no substantive content about Black Bears','boss'),
('https://crimsondesert.wiki.fextralife.com/Quests','Quests','nav-only page listing quests without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Main_Quests','Main_Quests','nav-only page listing quest categories','quest'),
('https://crimsondesert.wiki.fextralife.com/Faction_Quests','Faction_Quests','nav-only page listing quest categories','quest'),
('https://crimsondesert.wiki.fextralife.com/Everfrost','Everfrost','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Forest_of_Wolves','Forest_of_Wolves','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Halssius_Trading_Post','Halssius_Trading_Post','nav-only location listing without substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_3_Pailune','Subcontent:All_Abyss_Artifact_Locations_3_Pailune','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_4_Crimson_Desert','Subcontent:All_Abyss_Artifact_Locations_4_Crimson_Desert','nav-only page with minimal substantive content about artifact locations','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_5_Delesyia','Subcontent:All_Abyss_Artifact_Locations_5_Delesyia','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_7_Tab_7','Subcontent:All_Abyss_Artifact_Locations_7_Tab_7','nav-only, no substantive content about artifacts or locations','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Bosses','Category:Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Faction_Quests','Category:Faction_Quests','nav-only category listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Factions','Category:Factions','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Main_Quests','Category:Main_Quests','nav-only category listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Vendors','Category:Vendors','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:World_Information','Category:World_Information','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Grain_Bowl','Grain_Bowl','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Hexe_Marie','Hexe_Marie','excerpt is nav-only (boss list), no substantive content about Hexe Marie','character'),
('https://crimsondesert.wiki.fextralife.com/Hornsplitter%27s_Guards','Hornsplitter''s_Guards','nav-only faction listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/House_Felix','House_Felix','nav-only with faction overview; lacks specific quest/character/location details','character'),
('https://crimsondesert.wiki.fextralife.com/House_Grace','House_Grace','nav-only page with faction listings, no substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/House_Lanford','House_Lanford','nav-only page with faction listings, no substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Inksworth_Bindery','Inksworth_Bindery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Delesyia','Interactive_Map_Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Demeniss','Interactive_Map_Demeniss','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Hernand','Interactive_Map_Hernand','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Pailune','Interactive_Map_Pailune','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Kharonso_Troll_Alliance','Kharonso_Troll_Alliance','nav-only faction listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Reunion','Reunion','nav-only page listing quest names without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Kharonso','Kharonso','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Ivynook','Ivynook','nav-only page listing locations without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Key+Items','Key Items','nav-only page listing key items category without substantive content about specific items','item'),
('https://crimsondesert.wiki.fextralife.com/Woman_in_White','Woman_in_White','nav-only page listing quests without substantive content about Woman in White character or lore.','quest'),
('https://crimsondesert.wiki.fextralife.com/Where_the_Light_Leads','Where_the_Light_Leads','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Memory_Fragment','Memory_Fragment','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Greymanes%27_New_Fangs','The_Greymanes''_New_Fangs','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Chance_to_Make_a_Fortune','Chance_to_Make_a_Fortune','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Balder%27s_Request','Balder''s_Request','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Bounty_Notice:_Billy','Bounty_Notice:_Billy','nav-only page listing quests without substantive content about Billy bounty','quest'),
('https://crimsondesert.wiki.fextralife.com/First_Trial_of_Trust','First_Trial_of_Trust','nav-only page with quest list, no substantive content about the specific quest.','quest'),
('https://crimsondesert.wiki.fextralife.com/Troubled_Count','Troubled_Count','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/One-Handed+Weapons','One-Handed Weapons','nav-only - excerpt shows category listing of weapons without substantive details about a specific item.','item'),
('https://crimsondesert.wiki.fextralife.com/Bright_Red_Dye_(Recipe)','Bright_Red_Dye_(Recipe)','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Bullet_(Recipe)','Bullet_(Recipe)','nav-only list without recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Headgear','Category:Headgear','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Dark_Red_Dye_(Recipe)','Dark_Red_Dye_(Recipe)','nav-only (excerpt is primarily recipe list without substantive Dark Red Dye details)','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Guides_and_Walkthrough','Category:Guides_and_Walkthrough','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1633&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=137&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Main+Quests','Main Quests','nav-only list of quests without substantive details','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=295&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=307&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1611&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1636&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=457&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=452&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=422&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1415&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1624&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1630&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=406&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=450&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=429&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1414&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1625&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1631&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1638&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=441&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=437&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=430&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1426&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=838&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=356&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=467&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=469&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1404&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=483&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=478&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1225&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=497&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=498&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=499&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=380&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=384&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=391&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=301&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=839&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=504&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=362&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=417&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Snail','Snail','nav-only list of gatherables without substantive snail info','recipe'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/Guides_and_Walkthrough','Guides_and_Walkthrough','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_1_Provisions','Subcontent:Crafting_Guide_1_Provisions','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_2_Pailune','Subcontent:Vendors_2_Pailune','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_3_Demeniss','Subcontent:Vendors_3_Demeniss','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_4_Delesyia','Subcontent:Vendors_4_Delesyia','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_5_Crimson_Desert','Subcontent:Vendors_5_Crimson_Desert','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_6_The_Abyss','Subcontent:Vendors_6_The_Abyss','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Walkthrough_4_Chapter_3:_Howling_Hill','Subcontent:Walkthrough_4_Chapter_3:_Howling_Hill','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Bounty_Notice_-_Billy','Bounty_Notice_-_Billy','nav-only; mostly lists of items/links without substantive content about the bounty notice itself.','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Collectibles','Category:Collectibles','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Metal_Ware','Metal_Ware','nav-only list of collectibles without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Scales','Scales','nav-only list of collectibles without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Stacked_Glazed_Bowls','Stacked_Glazed_Bowls','nav-only list of collectibles without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Abyss_Core','Category:Abyss_Core','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Gloves','Gloves','nav-only, mostly navigation/category structure without substantive gloves content','item'),
('https://crimsondesert.wiki.fextralife.com/Weapon_Duel:_Spear','Weapon_Duel:_Spear','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Indomitable+Will','Indomitable Will','nav-only page with link list, no substantive content about "Indomitable Will"','quest'),
('https://crimsondesert.wiki.fextralife.com/Silver+Trigger','Silver Trigger','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Steel+Fist','Steel Fist','nav-only page with link lists, no substantive item info','quest'),
('https://crimsondesert.wiki.fextralife.com/Category:Locations','Category:Locations','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=419&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1410&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=985&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=412&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=414&amp;code=mapA','Interactive Map','nav-only page with general tool description','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1246&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=426&amp;code=mapA','Interactive Map','nav-only page with general tool description','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=425&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=418&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=991&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=988&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=998&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1006&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1428&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Tranan','Tranan','nav-only; appears to be item drops table and NPC list without substantive content about Tranan itself.','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=421&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=501&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=300&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=222&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=488&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=491&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=500&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_2_Alchemy','Subcontent:Crafting_Guide_2_Alchemy','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_3_Tools','Subcontent:Crafting_Guide_3_Tools','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_4_Equipment','Subcontent:Crafting_Guide_4_Equipment','nav-only page with minimal substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_5_Abyss_Cores','Subcontent:Crafting_Guide_5_Abyss_Cores','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_6_Kuku_Pot','Subcontent:Crafting_Guide_6_Kuku_Pot','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_7_Dyes','Subcontent:Crafting_Guide_7_Dyes','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=385&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Obsession_and_Madness','Obsession_and_Madness','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Perwin_Prison_Camp','Perwin_Prison_Camp','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Perwin_Trading_Post','Perwin_Trading_Post','nav-only location listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Pot','Pot','nav-only list of collectibles without substantive pot info','character'),
('https://crimsondesert.wiki.fextralife.com/Scholastone_Institute_(Faction)','Scholastone_Institute_(Faction)','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Secret_at_the_Church','Secret_at_the_Church','excerpt is nav-only, no substantive quest content visible','character'),
('https://crimsondesert.wiki.fextralife.com/Senia','Senia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Shot_Contest-Bow','Shot_Contest-Bow','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Shot_Contest:_Bow','Shot_Contest:_Bow','excerpt is nav-only, no substantive content about the minigame','character'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/World_Information','World_Information','nav-only','character')
ON CONFLICT (source_url) DO NOTHING;

INSERT INTO phase1c_manual_review_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Memory+Fragment','Memory Fragment','Mixed content about quest steps, items, and mechanics without clear primary focus.','quest'),
('https://crimsondesert.wiki.fextralife.com/House+Serkis','House Serkis','nav/faction overview without specific character/quest/location focus','character')
ON CONFLICT (source_url) DO NOTHING;
