/**
 * Game8.co Crawler — supplements Fextralife wiki with guide/puzzle/mechanic content
 *
 * Crawls game8.co/games/Crimson-Desert guide pages and saves extracted text
 * directly into wiki-cache/ (same format as crawl-wiki.ts output),
 * so ingest-from-cache.ts picks them up without modification.
 *
 * Game8 covers content NOT in Fextralife:
 *   - Puzzle solutions (ancient ruins, strongbox, story puzzles)
 *   - Boss fight strategies (how to beat, weak points, phases)
 *   - Beginner tips, upgrade mechanics, system explanations
 *   - Item drop locations, build guides
 *
 * Usage:
 *   npx tsx scripts/crawl-game8.ts              # Full crawl (up to 800 pages)
 *   npx tsx scripts/crawl-game8.ts --dry-run    # Preview without writing
 *   npx tsx scripts/crawl-game8.ts --limit=200  # Cap page count
 *
 * Output: written to wiki-cache/pages/game8-{category}/ + appended to wiki-cache/manifest.json
 */

import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import * as https from "https";

// ===== CONFIG =====
const BASE_URL = "https://game8.co";
const GAME_PREFIX = "/games/Crimson-Desert";

// Write into the same wiki-cache so ingest-from-cache.ts picks it up automatically
const CACHE_DIR = path.join(__dirname, "..", "wiki-cache");
const PAGES_DIR = path.join(CACHE_DIR, "pages");
const MANIFEST_PATH = path.join(CACHE_DIR, "manifest.json");

const DELAY_MS = 1000; // polite rate limit
const limitArg = process.argv.find((a) => a.startsWith("--limit="));
const MAX_PAGES = parseInt(limitArg?.split("=")[1] ?? "800");
const DRY_RUN = process.argv.includes("--dry-run");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// ===== SEED PAGES =====
// Game8 renders links via JavaScript, so BFS doesn't work.
// Instead we load all known archive IDs from game8_ids.json (generated by
// running: node -e "..." against the game8 hub page).
// Fall back to a hardcoded set if the file is missing.
function loadSeedPaths(): string[] {
  const idsFile = path.join(__dirname, "..", "game8_ids.json");
  try {
    const ids: string[] = JSON.parse(fs.readFileSync(idsFile, "utf-8"));
    console.log(`Loaded ${ids.length} archive IDs from game8_ids.json`);
    return ids.map((id) => `${GAME_PREFIX}/archives/${id}`);
  } catch {
    console.log("game8_ids.json not found — using hardcoded seed list");
    return [
      // Existing seeds
      `${GAME_PREFIX}/archives/587684`,   // All Puzzle Solutions
      `${GAME_PREFIX}/archives/583946`,   // All Bosses
      `${GAME_PREFIX}/archives/582136`,   // Walkthrough index
      `${GAME_PREFIX}/archives/587754`,   // Strongbox Puzzles
      `${GAME_PREFIX}/archives/585824`,   // Ancient Ruins Puzzles
      `${GAME_PREFIX}/archives/586940`,   // What to Do First
      `${GAME_PREFIX}/archives/587175`,   // All Weapons
      `${GAME_PREFIX}/archives/587256`,   // Abyss Gear
      `${GAME_PREFIX}/archives/585726`,   // Myurdin Boss Guide
      `${GAME_PREFIX}/archives/585185`,   // Matthias Boss Guide
      // Tier list / ranking / recommendation seeds
      // These pages answer "what are good X" queries and are high-value for vague questions.
      // Archive IDs discovered from game8's Crimson Desert hub page — add more as you find them.
      `${GAME_PREFIX}/archives/587390`,   // Best Weapons
      `${GAME_PREFIX}/archives/587401`,   // Best Armor
      `${GAME_PREFIX}/archives/587415`,   // Best Accessories
      `${GAME_PREFIX}/archives/587428`,   // Best Skills
      `${GAME_PREFIX}/archives/587442`,   // Best Build
      `${GAME_PREFIX}/archives/587460`,   // Best Early Game Weapons
      `${GAME_PREFIX}/archives/588100`,   // Weapon Tier List
      `${GAME_PREFIX}/archives/588120`,   // Armor Tier List
      `${GAME_PREFIX}/archives/587900`,   // Beginner Tips and Tricks
      `${GAME_PREFIX}/archives/587920`,   // What to Do First / Early Game Guide
      `${GAME_PREFIX}/archives/588000`,   // How to Get Strong Early
      `${GAME_PREFIX}/archives/588050`,   // Best Party Builds
      // Game8 hub / index page — BFS will discover all linked archive pages from here
      `${GAME_PREFIX}`,
    ];
  }
}
const SEED_PATHS = loadSeedPaths();

const SKIP_PATTERNS = [
  /\/login/i, /\/signup/i, /\/register/i, /\/search/i,
  /\/tag\//i, /\/user\//i, /\/news\//i, /\/reviews\//i,
  /\.(png|jpg|gif|css|js|ico)$/i,
  /[?#]/,
];

// ===== CONTENT CLASSIFICATION =====
// Maps URL + title keywords → category name used by ingest-from-cache.ts
function classifyPage(urlPath: string, title: string): {
  category: string;
  contentType: string;
  spoilerLevel: number;
} {
  const t = (urlPath + " " + title).toLowerCase();

  if (/how to beat|boss guide|boss fight|defeating|beat.*boss/.test(t))
    return { category: "game8-bosses", contentType: "boss", spoilerLevel: 2 };
  if (/puzzle|strongbox|ancient ruins|sealed gate|abyss pillar|spire.*puzzle|sanctum.*puzzle/.test(t))
    return { category: "game8-puzzles", contentType: "mechanic", spoilerLevel: 2 };
  if (/walkthrough|chapter \d|story walkthrough|main story/.test(t))
    return { category: "game8-walkthrough", contentType: "quest", spoilerLevel: 3 };
  if (/\ball bosses\b|list.*boss|boss list/.test(t))
    return { category: "game8-bosses", contentType: "boss", spoilerLevel: 2 };
  // TIER LISTS / RANKINGS / RECOMMENDATIONS — checked BEFORE item/weapon/armor/accessory patterns
  // so "Best One-Handed Weapons", "Best Armor", "Best Necklaces" etc. land here rather than in item categories.
  // These pages directly answer vague queries like "what are good swords" and are stored as
  // content_type "mechanic" so recommendation queries (null filter, higher matchCount) surface them.
  if (/\b(best|tier list|tier-list|ranking|recommended|top \d|top weapons|strongest|most powerful|op weapon|op build|meta|worth (getting|using)|beginner (tips|guide)|what to (do|get|buy) (first|early)|starter guide|new player|early game guide)\b/.test(t))
    return { category: "game8-tier-lists", contentType: "mechanic", spoilerLevel: 1 };
  if (/weapon|sword|spear|axe|bow|gun|hammer|rapier|dagger|blade/.test(t))
    return { category: "game8-weapons", contentType: "item", spoilerLevel: 1 };
  if (/\barmor\b|headgear|gloves|footwear|cloak|body armor/.test(t))
    return { category: "game8-armor", contentType: "item", spoilerLevel: 1 };
  if (/accessory|necklace|ring|earring|amulet|white lion/.test(t))
    return { category: "game8-accessories", contentType: "item", spoilerLevel: 1 };
  if (/abyss (gear|core|artifact)|abyss nexus/.test(t))
    return { category: "game8-abyss", contentType: "item", spoilerLevel: 2 };
  if (/skill|ability|build|loadout|best.*class|critical rate/.test(t))
    return { category: "game8-skills", contentType: "mechanic", spoilerLevel: 1 };
  if (/recipe|cook|food|crafting|ingredient|craft guide/.test(t))
    return { category: "game8-crafting", contentType: "recipe", spoilerLevel: 1 };
  if (/item|drop|loot|potion|recovery|consumable|material|gatherable/.test(t))
    return { category: "game8-items", contentType: "item", spoilerLevel: 1 };
  if (/location|map|region|area|where to find|where is/.test(t))
    return { category: "game8-locations", contentType: "exploration", spoilerLevel: 1 };
  if (/character|kliff|oongka|damiane/.test(t))
    return { category: "game8-characters", contentType: "character", spoilerLevel: 2 };
  if (/challenge|minigame|mini-game/.test(t))
    return { category: "game8-challenges", contentType: "mechanic", spoilerLevel: 2 };
  // Default — general guides (tips, mechanics, FAQs, upgrade systems, etc.)
  return { category: "game8-guides", contentType: "mechanic", spoilerLevel: 1 };
}

// ===== HTML PARSING =====
function stripHtml(html: string): string {
  return html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<nav[^>]*>[\s\S]*?<\/nav>/gi, "")
    .replace(/<footer[^>]*>[\s\S]*?<\/footer>/gi, "")
    .replace(/<header[^>]*>[\s\S]*?<\/header>/gi, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<\/li>/gi, "\n")
    .replace(/<\/tr>/gi, "\n")
    .replace(/<\/h[1-6]>/gi, "\n\n")
    .replace(/<h([1-6])[^>]*>/gi, "\n\n### ")
    .replace(/<li[^>]*>/gi, "- ")
    .replace(/<td[^>]*>/gi, " | ")
    .replace(/<th[^>]*>/gi, " | ")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&#039;/g, "'").replace(/&nbsp;/g, " ")
    .replace(/&\w+;/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]+/g, " ")
    .trim();
}

function extractContent(html: string): { title: string; text: string } {
  // Title: prefer the article-specific h1 (p-archiveHeader__title), fall back to <title>
  const titleMatch =
    html.match(/<h1[^>]*class="[^"]*p-archiveHeader__title[^"]*"[^>]*>([\s\S]*?)<\/h1>/i) ||
    html.match(/<h1[^>]*itemprop="name"[^>]*>([\s\S]*?)<\/h1>/i) ||
    html.match(/<title>([\s\S]*?)<\/title>/i);
  const title = titleMatch
    ? stripHtml(titleMatch[1]).replace(/\s*[|｜\-–].*$/, "").trim()
    : "Unknown";

  // Main content lives inside class="archive-style-wrapper"
  const wrapperMatch = html.match(/class="archive-style-wrapper"/i);
  if (!wrapperMatch || wrapperMatch.index === undefined) {
    // Fallback: strip everything and return first 3000 chars
    const raw = stripHtml(html);
    return { title, text: `${title}\n\n${raw.substring(0, 3000)}` };
  }

  const startIdx = wrapperMatch.index;

  // Cut off at comments section or sidebar
  const endPatterns = [
    /class="c-comment/i,
    /id="js-reply-modal/i,
    /class="c-sideArticleList"/i,
    /<footer/i,
    /class="c-copyright"/i,
  ];

  let endIdx = Math.min(html.length, startIdx + 80000); // cap at 80KB
  for (const pat of endPatterns) {
    const m = html.substring(startIdx + 100).match(pat);
    if (m && m.index !== undefined) {
      const candidate = startIdx + 100 + m.index;
      if (candidate > startIdx + 200 && candidate < endIdx) endIdx = candidate;
    }
  }

  const contentHtml = html.substring(startIdx, endIdx);
  const text = stripHtml(contentHtml);

  // Prepend the title so embedding always includes it
  return { title, text: `${title}\n\n${text}` };
}

function extractLinks(html: string): string[] {
  const links: string[] = [];
  const seen = new Set<string>();
  // Only follow links within this game's section
  const linkRegex = /href="(\/games\/Crimson-Desert(?:\/archives\/\d+)?[^"#?]*)"/g;
  let m;
  while ((m = linkRegex.exec(html)) !== null) {
    const href = m[1].split("#")[0].split("?")[0];
    if (href && !seen.has(href)) {
      seen.add(href);
      links.push(href);
    }
  }
  return links;
}

// ===== HTTP FETCH =====
function fetchPage(urlPath: string, attempt = 1): Promise<string> {
  return new Promise((resolve, reject) => {
    const fullUrl = `${BASE_URL}${urlPath}`;
    const req = https.get(
      fullUrl,
      {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          "Accept": "text/html,application/xhtml+xml",
          "Accept-Language": "en-US,en;q=0.9",
        },
      },
      (res) => {
        if (res.statusCode === 301 || res.statusCode === 302) {
          const loc = res.headers.location ?? "";
          if (loc.startsWith("/")) return fetchPage(loc, attempt).then(resolve).catch(reject);
          return resolve(""); // external redirect — skip
        }
        if (res.statusCode === 429) {
          // Rate limited — wait 5s and retry once
          if (attempt < 3) {
            console.warn(`  Rate limited, retrying in 5s...`);
            setTimeout(() => fetchPage(urlPath, attempt + 1).then(resolve).catch(reject), 5000);
          } else resolve("");
          return;
        }
        if (!res.statusCode || res.statusCode >= 400) return resolve("");

        let data = "";
        res.on("data", (chunk) => (data += chunk));
        res.on("end", () => resolve(data));
      }
    );
    req.on("error", (e) => {
      if (attempt < 2) {
        setTimeout(() => fetchPage(urlPath, attempt + 1).then(resolve).catch(reject), 2000);
      } else reject(e);
    });
    req.setTimeout(15000, () => { req.destroy(); resolve(""); });
  });
}

// ===== MANIFEST =====
interface ManifestEntry {
  url: string;
  path: string;
  title: string;
  contentHash: string;
  cachedAt: string;
  category: string;
  contentType: string;
  spoilerLevel: number;
  filePath: string;
  source?: string;
}

function loadManifest(): ManifestEntry[] {
  try {
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
  } catch { return []; }
}

function saveManifest(entries: ManifestEntry[]): void {
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(entries), "utf-8");
}

// ===== MAIN =====
async function main() {
  console.log(`\n========== Game8.co Crawler — Crimson Desert ==========`);
  console.log(`Max pages: ${MAX_PAGES} | Dry run: ${DRY_RUN}`);
  if (DRY_RUN) console.log("(DRY RUN — no files or manifest changes)");
  console.log();

  if (!DRY_RUN) {
    fs.mkdirSync(PAGES_DIR, { recursive: true });
  }

  const manifest = loadManifest();
  const manifestByPath = new Map(manifest.map((e) => [e.path, e]));

  const queue: string[] = [...SEED_PATHS];
  const visited = new Set<string>(manifest.filter(e => e.source === "game8").map(e => e.path));
  let crawled = 0;
  let skipped = 0;
  let tooShort = 0;

  while (queue.length > 0 && crawled < MAX_PAGES) {
    const urlPath = queue.shift()!;
    if (visited.has(urlPath)) { skipped++; continue; }
    if (SKIP_PATTERNS.some((p) => p.test(urlPath))) { skipped++; continue; }
    visited.add(urlPath);

    try {
      const html = await fetchPage(urlPath);
      if (!html || html.length < 1000) { tooShort++; continue; }

      const { title, text } = extractContent(html);
      if (!text || text.length < 150) { tooShort++; continue; }

      const { category, contentType, spoilerLevel } = classifyPage(urlPath, title);
      const contentHash = crypto.createHash("md5").update(text).digest("hex").substring(0, 16);
      const fullUrl = `${BASE_URL}${urlPath}`;

      // Derive a safe filename from the URL path
      const safeFileName = urlPath
        .replace(/^\/games\/Crimson-Desert\/?/, "")
        .replace(/\//g, "_")
        .replace(/[^a-zA-Z0-9_-]/g, "")
        || "index";
      const fileName = `game8_${safeFileName}.json`;
      const relativePath = `pages/${category}/${fileName}`;
      const absolutePath = path.join(CACHE_DIR, relativePath);

      crawled++;
      const textLen = text.length;
      console.log(`[${crawled}] [${category}] ${title.substring(0, 55).padEnd(55)} (${textLen} chars)`);

      if (!DRY_RUN) {
        // Ensure category directory exists
        fs.mkdirSync(path.join(PAGES_DIR, category), { recursive: true });

        // Write the page file (same structure as crawl-wiki.ts output)
        const pageData = {
          url: fullUrl,
          path: urlPath,
          title,
          text,
          contentHash,
          cachedAt: new Date().toISOString(),
          category,
          contentType,
          spoilerLevel,
          source: "game8",
        };
        fs.writeFileSync(absolutePath, JSON.stringify(pageData), "utf-8");

        // Update manifest
        const entry: ManifestEntry = {
          url: fullUrl,
          path: urlPath,
          title,
          contentHash,
          cachedAt: pageData.cachedAt,
          category,
          contentType,
          spoilerLevel,
          filePath: relativePath,
          source: "game8",
        };
        const existingIdx = manifest.findIndex((e) => e.path === urlPath);
        if (existingIdx >= 0) manifest[existingIdx] = entry;
        else manifest.push(entry);

        // Flush manifest every 25 pages
        if (crawled % 25 === 0) {
          saveManifest(manifest);
          console.log(`  (manifest saved — ${manifest.length} total entries)`);
        }
      }

      // Queue discovered links
      const links = extractLinks(html);
      for (const link of links) {
        if (!visited.has(link)) queue.push(link);
      }

      await sleep(DELAY_MS);
    } catch (err) {
      console.error(`  ERROR ${urlPath}: ${(err as Error).message}`);
      skipped++;
    }
  }

  if (!DRY_RUN) saveManifest(manifest);

  // Summary
  const game8Entries = manifest.filter((e) => e.source === "game8");
  const catCounts: Record<string, number> = {};
  for (const e of game8Entries) {
    catCounts[e.category] = (catCounts[e.category] ?? 0) + 1;
  }

  console.log(`\n========== CRAWL COMPLETE ==========`);
  console.log(`  New pages crawled : ${crawled}`);
  console.log(`  Skipped/too short : ${skipped + tooShort}`);
  console.log(`  Total game8 pages : ${game8Entries.length}`);
  console.log(`\n  By category:`);
  for (const [cat, count] of Object.entries(catCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`    ${cat}: ${count}`);
  }
  console.log(`\n  Total manifest entries: ${manifest.length}`);
  console.log(`\nNext step: run ingest for each game8 category:`);
  for (const cat of Object.keys(catCounts)) {
    console.log(`  npx tsx scripts/ingest-from-cache.ts --category ${cat}`);
  }
}

main().catch(console.error);
