INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=72&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Equipment','Category:Equipment','nav-only category page with subcategory listings','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=641&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=111&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=15&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','item'),
('https://crimsondesert.wiki.fextralife.com/Key_Items','Key_Items','nav-only page listing key items category without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Abyss_Item','Abyss_Item','nav-only category listing without substantive item details','item'),
('https://crimsondesert.wiki.fextralife.com/Horn_Thief','Horn_Thief','nav-only list of key items without substantive content about Horn Thief itself','item'),
('https://crimsondesert.wiki.fextralife.com/Key','Key','nav-only page listing key items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Lost_Letter','Lost_Letter','nav-only list of key items without substantive content about Lost Letter itself','item'),
('https://crimsondesert.wiki.fextralife.com/Seal_of_Greed_-_Goldleaf_Merchant_Guild','Seal_of_Greed_-_Goldleaf_Merchant_Guild','nav-only page listing key items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Stolen_Cows','Stolen_Cows','nav-only page listing key items without quest details','item'),
('https://crimsondesert.wiki.fextralife.com/Tavern_Ledger','Tavern_Ledger','nav-only list of items without substantive content about the Tavern Ledger itself','item'),
('https://crimsondesert.wiki.fextralife.com/Ugmon%27s_Note','Ugmon''s_Note','nav-only, no substantive content about the item itself','item'),
('https://crimsondesert.wiki.fextralife.com/Unsealed_Letter','Unsealed_Letter','nav-only page with item list, no substantive content about the item itself','item'),
('https://crimsondesert.wiki.fextralife.com/Wisdom_between_Donation_and_Fruition','Wisdom_between_Donation_and_Fruition','nav-only page listing items without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Locations','Locations','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Arboria_Craftshop','Arboria_Craftshop','nav-only location stub with minimal substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/NPCs','NPCs','nav-only page listing NPC mechanics, not a specific NPC','character'),
('https://crimsondesert.wiki.fextralife.com/Calphade_Gate','Calphade_Gate','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=324&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=523&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=404&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=884&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=312&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=304&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=539&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=305&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=306&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=313&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=775&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=314&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=315&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=551&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=793&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=528&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=316&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=53&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=188&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=319&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=463&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=327&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=13&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=66&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=262&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=552&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=555&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=537&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Precipice+of+Echoes+Ruins','Precipice of Echoes Ruins','nav-only page listing challenges/locations without substantive content about the specific location itself.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=455&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=510&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=928&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=511&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=933&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=479&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=941&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=934&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=449&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=525&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=517&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=541&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Delkin','Delkin','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Renee','Renee','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=197&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=376&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Annabella','Annabella','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=942&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood+Waterside+Ruins','Duskwood Waterside Ruins','nav-only page with quest/location list, no substantive content about the location itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1431&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1411&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1013&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=936&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=935&amp;code=mapA','Interactive Map','nav-only page with map tool, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=932&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=937&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=938&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Abacus','Abacus','nav-only page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Horse_Items','Category:Horse_Items','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Notepad','Notepad','nav-only page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/Equipment','Equipment','nav-only search results page with no substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Abyss_Core_1_Abyss_Core_Gallery','Subcontent:Abyss_Core_1_Abyss_Core_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Accessories_1_Accessories_Gallery','Subcontent:Accessories_1_Accessories_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Accessories_2_Accessories_Table','Subcontent:Accessories_2_Accessories_Table','nav-only page with minimal substantive content about accessories','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Pets_1_Pet_Types','Subcontent:Pets_1_Pet_Types','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Pets_2_Pet_Equipment','Subcontent:Pets_2_Pet_Equipment','nav-only with item list; no substantive mechanics or lore','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Tools_1_Tools_Gallery','Subcontent:Tools_1_Tools_Gallery','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Tools_2_Tools_Table','Subcontent:Tools_2_Tools_Table','nav-only page listing tools without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Unique_Weapons','Unique_Weapons','nav-only page listing weapon categories without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Alchemy_Recipes','Alchemy_Recipes','nav-only list of recipes without substantive details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Items','Category:Items','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:NPCs','Category:NPCs','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Recovery_Items','Category:Recovery_Items','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Drake_Wells','Drake_Wells','nav-only; excerpt is mostly NPC list without substantive Drake Wells content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Grania','Grania','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Grimrak','Grimrak','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Groks','Groks','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=507&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=509&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=303&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1812&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=138&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1501&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=514&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=444&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=446&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=533&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1427&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1632&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=219&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=447&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=208&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=223&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=221&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=241&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=217&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=294&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=220&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=519&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=198&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=199&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=244&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=156&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=243&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=157&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=158&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=145&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=149&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=146&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=143&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=160&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=151&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=114&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=289&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1417&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1634&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1653&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=364&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=127&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=142&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=302&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=529&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=532&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=530&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=531&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=296&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=308&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=297&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=309&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=298&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=310&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=299&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=311&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=259&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=366&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=139&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=194&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=136&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=365&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=141&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=210&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=167&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=548&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1413&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=549&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=164&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1403&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1412&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=168&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1668&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1753&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1684&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1113&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1667&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1700&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1666&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1685&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Bosses','Bosses','nav-only or system overview, not a specific boss','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1589&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1592&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1623&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1629&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1375&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Merchants','Merchants','nav-only list of merchants without substantive details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Consumables','Consumables','nav-only page listing consumable categories without specific item details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Force+Palm','Force Palm','nav-only list of skills without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Blacksmiths','Blacksmiths','nav-only page listing blacksmith NPCs without substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Guides+%26+Walkthrough','Guides & Walkthrough','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/FAQs','FAQs','nav-only page with system specs and links, no substantive game content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Crimson_Desert_Wiki','Crimson_Desert_Wiki','nav-only; excerpt is wiki homepage with general boss overview, not a specific subject.','boss'),
('https://crimsondesert.wiki.fextralife.com/Rock_Paper_Scissors','Rock_Paper_Scissors','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/New_Player_Help','New_Player_Help','nav-only guide page with mixed topics','mechanic'),
('https://crimsondesert.wiki.fextralife.com/General_Information','General_Information','nav-only page with minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/DLC','DLC','nav-only page listing DLC editions and items without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:General_Information','Category:General_Information','nav-only category page with minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_2_Xbox_Controls','Subcontent:Controls_2_Xbox_Controls','nav-only, control mapping reference without substantive gameplay explanation','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_3_PC_Controls','Subcontent:Controls_3_PC_Controls','nav-only, control mapping reference without substantive game content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Controls_4_Tab_4','Subcontent:Controls_4_Tab_4','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Arm_Wrestling','Arm_Wrestling','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Where_Rumors_Gather','Where_Rumors_Gather','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Abyss_without_Balance','Abyss_without_Balance','nav-only','quest')
ON CONFLICT (source_url) DO NOTHING;
