INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Abyss_Cresset_of_Meandering_Hills','Abyss_Cresset_of_Meandering_Hills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Missing_Companion','Missing_Companion','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Fresh_Start','A_Fresh_Start','nav-only page listing quest names without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Clear_Soup_(Recipe)','Clear_Soup_(Recipe)','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Greymanes_Reunited','Greymanes_Reunited','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Items','Items','nav-only page listing crafting/cooking systems, not a specific item','item'),
('https://crimsondesert.wiki.fextralife.com/House_Alfonso','House_Alfonso','nav-only page with faction listing, minimal substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Goddess_of_Abundance','Goddess_of_Abundance','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/The_Hunter%27s_Path','The_Hunter''s_Path','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_2_Greymanes','Subcontent:Faction_Quests_2_Greymanes','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_3_Pailune','Subcontent:Faction_Quests_3_Pailune','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_4_Demeniss','Subcontent:Faction_Quests_4_Demeniss','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_5_Delesyia','Subcontent:Faction_Quests_5_Delesyia','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Faction_Quests_6_Crimson_Desert','Subcontent:Faction_Quests_6_Crimson_Desert','nav-only page listing quest names without substantive details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Quests','Category:Quests','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Root%27s_End_(Challenge)','Root''s_End_(Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sanctorum_of_Insight_(Challenge)','Sanctorum_of_Insight_(Challenge)','nav-only list with minimal substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Detailed_Glance','A_Detailed_Glance','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Haven_Past_the_Snowfall','Haven_Past_the_Snowfall','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Duskwood_Hill_Ruins','Duskwood_Hill_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering_Hills_Ruins','Meandering_Hills_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sunrise_Plains_Ruins','Sunrise_Plains_Ruins','nav-only page listing quests/challenges without substantive location details','quest'),
('https://crimsondesert.wiki.fextralife.com/Arboria_Forest_Ruins','Arboria_Forest_Ruins','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire_of_Insight_(Challenge)','Spire_of_Insight_(Challenge)','nav-only page listing challenges/locations without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire_of_Clockwork_(Challenge)','Spire_of_Clockwork_(Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Rainbow_Across_the_Sky','Rainbow_Across_the_Sky','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Flash','Flash','nav-only; mostly challenge list without substantive Flash content','quest'),
('https://crimsondesert.wiki.fextralife.com/Recipes','Recipes','nav-only page listing recipe categories without specific recipe details','recipe'),
('https://crimsondesert.wiki.fextralife.com/Animal_Meat','Animal_Meat','nav-only, appears to be a list of quests/items without substantive content about Animal Meat itself','quest'),
('https://crimsondesert.wiki.fextralife.com/Silver_Trigger','Silver_Trigger','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Steel_Fist','Steel_Fist','nav-only page with list of quest/location names','quest'),
('https://crimsondesert.wiki.fextralife.com/A_Bloom_of_High_Stakes','A_Bloom_of_High_Stakes','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Guides_and_Walkthrough','Guides_and_Walkthrough','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/In_Ashes','In_Ashes','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Realm_of_Uncertainty','Realm_of_Uncertainty','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Characters','Characters','nav-only page listing characters without substantive detail','character'),
('https://crimsondesert.wiki.fextralife.com/Character_Information','Character_Information','nav-only page listing character skills without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Delesyia','Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Crimson_Desert','Crimson_Desert','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Sanctorum+of+Insight+(Challenge)','Sanctorum of Insight (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Axiom+Archive+(Challenge)','Axiom Archive (Challenge)','nav-only page with link lists, no substantive content about Axiom Archive itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Crescent+Skybridge+(Challenge)','Crescent Skybridge (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Arboria+Forest+Ruins','Arboria Forest Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Root''s+End+(Challenge)','Root''s End (Challenge)','excerpt is nav-only list without substantive content about Root''s End','quest'),
('https://crimsondesert.wiki.fextralife.com/Haven+Past+the+Snowfall','Haven Past the Snowfall','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood+Hill+Ruins','Duskwood Hill Ruins','nav-only - excerpt is primarily a list of linked page names without substantive content about the location itself.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Sunrise+Plains+Ruins','Sunrise Plains Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Dragon''s+Stone+Chamber+Ruins','Dragon''s Stone Chamber Ruins','nav-only page with quest/location list, no substantive content about the ruins themselves','quest'),
('https://crimsondesert.wiki.fextralife.com/Keeping+Balance+on+the+Wind','Keeping Balance on the Wind','nav-only page with quest/location list, no substantive content about the titled topic','quest'),
('https://crimsondesert.wiki.fextralife.com/Factions','Factions','nav-only page listing factions without substantive details','boss'),
('https://crimsondesert.wiki.fextralife.com/Dancing+Blade+Shining+Shield+I','Dancing Blade Shining Shield I','nav-only page with link list, no substantive content about the item itself','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Animal+Meat','Animal Meat','excerpt is nav-only list without item details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/A+Bloom+of+High+Stakes','A Bloom of High Stakes','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Awestruck','Awestruck','nav-only page listing quests without substantive content about a specific subject.','quest'),
('https://crimsondesert.wiki.fextralife.com/Return','Return','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Howling+Hill','Howling Hill','nav-only - primarily lists quests without substantive location details','character'),
('https://crimsondesert.wiki.fextralife.com/Shield+of+Unchanging+Will+I','Shield of Unchanging Will I','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Side_Quests','Side_Quests','nav-only page listing side quests without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_1_Main_Bosses','Subcontent:Bosses_1_Main_Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_2_Side_Bosses','Subcontent:Bosses_2_Side_Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Bosses_3_Bosses_by_Region','Subcontent:Bosses_3_Bosses_by_Region','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_1_Duchy_of_Hernand','Subcontent:Factions_1_Duchy_of_Hernand','nav-only page with minimal substantive content about factions','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_2_Tribal_State_of_Pailune','Subcontent:Factions_2_Tribal_State_of_Pailune','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Factions_3_Continent_of_Pywel','Subcontent:Factions_3_Continent_of_Pywel','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_1_Animals_Gallery','Subcontent:Lifeforms_1_Animals_Gallery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_2_Land_Animals','Subcontent:Lifeforms_2_Land_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_3_Flying_Animals','Subcontent:Lifeforms_3_Flying_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_4_Aquatic_Animals','Subcontent:Lifeforms_4_Aquatic_Animals','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Lifeforms_5_Insects_and_Arthropods','Subcontent:Lifeforms_5_Insects_and_Arthropods','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Locations_1_List_of_all_Locations','Subcontent:Locations_1_List_of_all_Locations','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Locations_2_Locations_Gallery','Subcontent:Locations_2_Locations_Gallery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_3_Demeniss','Subcontent:NPCs_3_Demeniss','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_4_Delesyia','Subcontent:NPCs_4_Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_5_Crimson_Desert','Subcontent:NPCs_5_Crimson_Desert','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:NPCs_6_The_Abyss','Subcontent:NPCs_6_The_Abyss','nav-only page listing NPCs with minimal substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Supply_Tent','Supply_Tent','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/The_Missing_Seal','The_Missing_Seal','nav-only page listing quest names without substantive quest details','character'),
('https://crimsondesert.wiki.fextralife.com/Warspike_Spearmaker','Warspike_Spearmaker','nav-only page with location listings, no substantive content about the subject','character'),
('https://crimsondesert.wiki.fextralife.com/Projectiles','Projectiles','nav-only page with minimal substantive content about projectiles','item'),
('https://crimsondesert.wiki.fextralife.com/Tools','Tools','nav-only category page listing tools without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Armor','Armor','nav-only page with minimal substantive content about armor mechanics or specific items.','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=526&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=147&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=931&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1608&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1646&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Halssius_Apothecary','Halssius_Apothecary','nav-only location listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=542&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1815&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=387&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=382&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=398&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1416&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Trial_After_Trial','Trial_After_Trial','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Dark_Veil','The_Dark_Veil','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Kidnapped_Healer','Kidnapped_Healer','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Return_of_the_Comrade','Return_of_the_Comrade','excerpt is nav-only, no quest content visible','quest'),
('https://crimsondesert.wiki.fextralife.com/Traces_in_the_Manor','Traces_in_the_Manor','excerpt is nav-only, no substantive quest content visible','quest'),
('https://crimsondesert.wiki.fextralife.com/Hope_After_the_Draught','Hope_After_the_Draught','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Bustling_Hill','Bustling_Hill','nav-only page listing quests without substantive location info','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Words_of_Alustin','The_Words_of_Alustin','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Demenissian_Delegation','Demenissian_Delegation','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Three_Saints%27_Falls','Three_Saints''_Falls','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Anvil_Riverside_Terrace','Anvil_Riverside_Terrace','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Axiom_Archive','Axiom_Archive','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering_Hills','Meandering_Hills','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Hernand_Farmhouse','Hernand_Farmhouse','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Capra_Pasture','Capra_Pasture','nav-only location page with minimal substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Goldleaf_Tradepost','Goldleaf_Tradepost','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Goldleaf_Guildhouse','Goldleaf_Guildhouse','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Scrapfold','The_Scrapfold','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Coalvale_Workshop','Coalvale_Workshop','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Meshley_Trapsmith','Meshley_Trapsmith','nav-only page listing locations without substantive content about Meshley Trapsmith','quest'),
('https://crimsondesert.wiki.fextralife.com/Demeniss','Demeniss','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Wycliffe_Mappery','Wycliffe_Mappery','nav-only page listing locations without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Arrow_(Recipe)','Arrow_(Recipe)','nav-only list without recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Battered_Fish_(Recipe)','Battered_Fish_(Recipe)','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Battered_Vegetables_(Recipe)','Battered_Vegetables_(Recipe)','excerpt is nav-only list, no recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Lioncrest_Manor','Lioncrest_Manor','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Phoniel_Ranch','Phoniel_Ranch','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Thalwynd','Thalwynd','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/The_Sage%27s_Peak','The_Sage''s_Peak','nav-only location page with minimal substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Vellua','Vellua','nav-only page listing locations without substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Accessories','Accessories','nav-only category page listing accessories without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=407&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Sunset+Valley','Sunset Valley','nav-only page listing locations without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Axiom+Archive','Axiom Archive','nav-only page listing locations without substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1670&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1669&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1593&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1548&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1549&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1566&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1540&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1550&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1564&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=170&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=443&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=442&amp;code=mapA','Interactive Map','nav-only page with general tracker/tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=368&amp;code=mapA','Interactive Map','nav-only page with general tool description, not specific content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=360&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=369&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=445&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=363&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=371&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=392&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=393&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=543&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1536&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=984&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=451&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=373&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=396&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=508&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=370&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=405&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=402&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=410&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=381&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=379&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1418&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=395&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=386&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=413&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1405&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=388&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=415&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1502&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1503&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=372&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=357&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1492&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1591&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1496&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1497&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1498&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1499&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1654&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1750&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1777&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=78&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=960&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1810&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1799&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1649&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=502&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=544&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1806&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1811&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Meandering+Hills','Meandering Hills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1804&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1802&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1803&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1807&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=564&amp;code=mapA','Interactive Map','nav-only page with general tool description','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1797&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1801&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=515&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1805&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1808&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest')
ON CONFLICT (source_url) DO NOTHING;
