INSERT INTO phase1e_nav_only_candidates_20260425 (source_url, page_name, haiku_reason, old_content_type) VALUES
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1652&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=513&amp;code=mapA','Interactive Map','nav-only page with general tracker/checklist info','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=538&amp;code=mapA','Interactive Map','nav-only page describing a tool/tracker, not a specific game element','quest'),
('https://crimsondesert.wiki.fextralife.com/Spire+of+Insight+(Challenge)','Spire of Insight (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Sword+of+Trials+III','Sword of Trials III','nav-only page with challenge listings, minimal item details','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Spire+of+Ringing+Truth+(Challenge)','Spire of Ringing Truth (Challenge)','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=239&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=350&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=351&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1406&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=399&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=416&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=427&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Theoric','Theoric','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Timberturner_Wainwright','Timberturner_Wainwright','nav-only page with ingredient lists and location links','recipe'),
('https://crimsondesert.wiki.fextralife.com/Tool_Blueprints','Tool_Blueprints','nav-only list of recipes without substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Ugmon','Ugmon','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Water_Strider','Water_Strider','nav-only list of gatherables without substantive Water Strider info','recipe'),
('https://crimsondesert.wiki.fextralife.com/Category:Character_Information','Category:Character_Information','nav-only category page with no substantive content','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Characters','Category:Characters','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Kliff_Skills','Category:Kliff_Skills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Skills','Category:Skills','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Precipice_of_Echoes_Ruins','Precipice_of_Echoes_Ruins','nav-only - excerpt is primarily a list of linked page names without substantive location information.','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Duskwood_Waterside_Ruins','Duskwood_Waterside_Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Steel_Mountains_Ruins','Steel_Mountains_Ruins','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/World_Information','World_Information','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Kearush_the_Slayer','Kearush_the_Slayer','excerpt is nav-only (boss list without strategy details)','boss'),
('https://crimsondesert.wiki.fextralife.com/Tenebrum','Tenebrum','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Abyss_Nexus','Abyss_Nexus','nav-only list of Abyss Nexus locations without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map','Interactive_Map','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Lifeforms','Lifeforms','nav-only or ingredient list without gameplay context','character'),
('https://crimsondesert.wiki.fextralife.com/Lore','Lore','nav-only page with minimal substantive lore content','boss'),
('https://crimsondesert.wiki.fextralife.com/Special:Categories','Special:Categories','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Enemies','Enemies','nav-only','boss'),
('https://crimsondesert.wiki.fextralife.com/Reed_Devil_(Faction)','Reed_Devil_(Faction)','nav-only; mostly faction list without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Southern_Bandits','Southern_Bandits','nav-only page listing factions without substantive content','boss'),
('https://crimsondesert.wiki.fextralife.com/Black_Bears','Black_Bears','nav-only page with faction listings, no substantive content about Black Bears','boss'),
('https://crimsondesert.wiki.fextralife.com/Quests','Quests','nav-only page listing quests without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Main_Quests','Main_Quests','nav-only page listing quest categories','quest'),
('https://crimsondesert.wiki.fextralife.com/Faction_Quests','Faction_Quests','nav-only page listing quest categories','quest'),
('https://crimsondesert.wiki.fextralife.com/Everfrost','Everfrost','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Forest_of_Wolves','Forest_of_Wolves','nav-only','exploration'),
('https://crimsondesert.wiki.fextralife.com/Halssius_Trading_Post','Halssius_Trading_Post','nav-only location listing without substantive content','exploration'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_3_Pailune','Subcontent:All_Abyss_Artifact_Locations_3_Pailune','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_4_Crimson_Desert','Subcontent:All_Abyss_Artifact_Locations_4_Crimson_Desert','nav-only page with minimal substantive content about artifact locations','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_5_Delesyia','Subcontent:All_Abyss_Artifact_Locations_5_Delesyia','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:All_Abyss_Artifact_Locations_7_Tab_7','Subcontent:All_Abyss_Artifact_Locations_7_Tab_7','nav-only, no substantive content about artifacts or locations','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Category:Bosses','Category:Bosses','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Faction_Quests','Category:Faction_Quests','nav-only category listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Factions','Category:Factions','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Main_Quests','Category:Main_Quests','nav-only category listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Category:Vendors','Category:Vendors','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Category:World_Information','Category:World_Information','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Grain_Bowl','Grain_Bowl','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Hexe_Marie','Hexe_Marie','excerpt is nav-only (boss list), no substantive content about Hexe Marie','character'),
('https://crimsondesert.wiki.fextralife.com/Hornsplitter%27s_Guards','Hornsplitter''s_Guards','nav-only faction listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/House_Felix','House_Felix','nav-only with faction overview; lacks specific quest/character/location details','character'),
('https://crimsondesert.wiki.fextralife.com/House_Grace','House_Grace','nav-only page with faction listings, no substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/House_Lanford','House_Lanford','nav-only page with faction listings, no substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Inksworth_Bindery','Inksworth_Bindery','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Delesyia','Interactive_Map_Delesyia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Demeniss','Interactive_Map_Demeniss','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Hernand','Interactive_Map_Hernand','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive_Map_Pailune','Interactive_Map_Pailune','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Kharonso_Troll_Alliance','Kharonso_Troll_Alliance','nav-only faction listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Reunion','Reunion','nav-only page listing quest names without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Kharonso','Kharonso','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Ivynook','Ivynook','nav-only page listing locations without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Key+Items','Key Items','nav-only page listing key items category without substantive content about specific items','item'),
('https://crimsondesert.wiki.fextralife.com/Woman_in_White','Woman_in_White','nav-only page listing quests without substantive content about Woman in White character or lore.','quest'),
('https://crimsondesert.wiki.fextralife.com/Where_the_Light_Leads','Where_the_Light_Leads','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Memory_Fragment','Memory_Fragment','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/The_Greymanes%27_New_Fangs','The_Greymanes''_New_Fangs','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Chance_to_Make_a_Fortune','Chance_to_Make_a_Fortune','nav-only page listing quest names without substantive content','quest'),
('https://crimsondesert.wiki.fextralife.com/Balder%27s_Request','Balder''s_Request','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Bounty_Notice:_Billy','Bounty_Notice:_Billy','nav-only page listing quests without substantive content about Billy bounty','quest'),
('https://crimsondesert.wiki.fextralife.com/First_Trial_of_Trust','First_Trial_of_Trust','nav-only page with quest list, no substantive content about the specific quest.','quest'),
('https://crimsondesert.wiki.fextralife.com/Troubled_Count','Troubled_Count','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/One-Handed+Weapons','One-Handed Weapons','nav-only - excerpt shows category listing of weapons without substantive details about a specific item.','item'),
('https://crimsondesert.wiki.fextralife.com/Bright_Red_Dye_(Recipe)','Bright_Red_Dye_(Recipe)','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Bullet_(Recipe)','Bullet_(Recipe)','nav-only list without recipe details','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Headgear','Category:Headgear','nav-only','item'),
('https://crimsondesert.wiki.fextralife.com/Dark_Red_Dye_(Recipe)','Dark_Red_Dye_(Recipe)','nav-only (excerpt is primarily recipe list without substantive Dark Red Dye details)','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Guides_and_Walkthrough','Category:Guides_and_Walkthrough','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1633&amp;code=mapA','Interactive Map','nav-only page with minimal substantive content about locations','item'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=137&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Main+Quests','Main Quests','nav-only list of quests without substantive details','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=295&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=307&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1611&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1636&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=457&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=452&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=422&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1415&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1624&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1630&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=406&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=450&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=429&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1414&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1625&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1631&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1638&amp;code=mapA','Interactive Map','nav-only page with interactive map tool, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=441&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=437&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=430&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1426&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=838&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=356&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=467&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=469&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1404&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=483&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=478&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1225&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=497&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=498&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=499&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=380&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=384&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=391&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=301&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=839&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content about specific subject','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=504&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=362&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=417&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Snail','Snail','nav-only list of gatherables without substantive snail info','recipe'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/Guides_and_Walkthrough','Guides_and_Walkthrough','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_1_Provisions','Subcontent:Crafting_Guide_1_Provisions','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_2_Pailune','Subcontent:Vendors_2_Pailune','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_3_Demeniss','Subcontent:Vendors_3_Demeniss','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_4_Delesyia','Subcontent:Vendors_4_Delesyia','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_5_Crimson_Desert','Subcontent:Vendors_5_Crimson_Desert','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Vendors_6_The_Abyss','Subcontent:Vendors_6_The_Abyss','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Walkthrough_4_Chapter_3:_Howling_Hill','Subcontent:Walkthrough_4_Chapter_3:_Howling_Hill','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Bounty_Notice_-_Billy','Bounty_Notice_-_Billy','nav-only; mostly lists of items/links without substantive content about the bounty notice itself.','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Collectibles','Category:Collectibles','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Metal_Ware','Metal_Ware','nav-only list of collectibles without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Scales','Scales','nav-only list of collectibles without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Stacked_Glazed_Bowls','Stacked_Glazed_Bowls','nav-only list of collectibles without substantive details','item'),
('https://crimsondesert.wiki.fextralife.com/Category:Abyss_Core','Category:Abyss_Core','nav-only category listing without substantive content','item'),
('https://crimsondesert.wiki.fextralife.com/Gloves','Gloves','nav-only, mostly navigation/category structure without substantive gloves content','item'),
('https://crimsondesert.wiki.fextralife.com/Weapon_Duel:_Spear','Weapon_Duel:_Spear','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Indomitable+Will','Indomitable Will','nav-only page with link list, no substantive content about "Indomitable Will"','quest'),
('https://crimsondesert.wiki.fextralife.com/Silver+Trigger','Silver Trigger','nav-only','quest'),
('https://crimsondesert.wiki.fextralife.com/Steel+Fist','Steel Fist','nav-only page with link lists, no substantive item info','quest'),
('https://crimsondesert.wiki.fextralife.com/Category:Locations','Category:Locations','nav-only','mechanic'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=419&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1410&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=985&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=412&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=414&amp;code=mapA','Interactive Map','nav-only page with general tool description','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1246&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=426&amp;code=mapA','Interactive Map','nav-only page with general tool description','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=425&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=418&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=991&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=988&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=998&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1006&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','boss'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=1428&amp;code=mapA','Interactive Map','nav-only page with mixed content overview','quest'),
('https://crimsondesert.wiki.fextralife.com/Tranan','Tranan','nav-only; appears to be item drops table and NPC list without substantive content about Tranan itself.','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=421&amp;code=mapA','Interactive Map','nav-only page with map tool, lacks substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=501&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=300&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=222&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=488&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=491&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=500&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','character'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_2_Alchemy','Subcontent:Crafting_Guide_2_Alchemy','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_3_Tools','Subcontent:Crafting_Guide_3_Tools','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_4_Equipment','Subcontent:Crafting_Guide_4_Equipment','nav-only page with minimal substantive content','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_5_Abyss_Cores','Subcontent:Crafting_Guide_5_Abyss_Cores','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_6_Kuku_Pot','Subcontent:Crafting_Guide_6_Kuku_Pot','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Subcontent:Crafting_Guide_7_Dyes','Subcontent:Crafting_Guide_7_Dyes','nav-only','recipe'),
('https://crimsondesert.wiki.fextralife.com/Interactive+Map?id=385&amp;code=mapA','Interactive Map','nav-only page with map interface, no specific subject content','quest'),
('https://crimsondesert.wiki.fextralife.com/Obsession_and_Madness','Obsession_and_Madness','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Perwin_Prison_Camp','Perwin_Prison_Camp','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Perwin_Trading_Post','Perwin_Trading_Post','nav-only location listing without substantive content','character'),
('https://crimsondesert.wiki.fextralife.com/Pot','Pot','nav-only list of collectibles without substantive pot info','character'),
('https://crimsondesert.wiki.fextralife.com/Scholastone_Institute_(Faction)','Scholastone_Institute_(Faction)','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Secret_at_the_Church','Secret_at_the_Church','excerpt is nav-only, no substantive quest content visible','character'),
('https://crimsondesert.wiki.fextralife.com/Senia','Senia','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Shot_Contest-Bow','Shot_Contest-Bow','nav-only','character'),
('https://crimsondesert.wiki.fextralife.com/Shot_Contest:_Bow','Shot_Contest:_Bow','excerpt is nav-only, no substantive content about the minigame','character'),
('https://crimsondesert.wiki.fextralife.com/Special:Search/World_Information','World_Information','nav-only','character')
ON CONFLICT (source_url) DO NOTHING;
